<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>AVRControl</RootNamespace>
		<AssemblyName>AVRControl</AssemblyName>
		<ApplicationIcon>AVRControl.ico</ApplicationIcon>
		<Deterministic>true</Deterministic>

		<Version>1.5.2</Version>
		<Authors>SAMDestroy</Authors>
		<Company>SAMDestroy</Company>
		<Product>AVRControl</Product>
		<Description>Control your Denon or Marantz AVR via Telnet</Description>
		<Copyright>Copyright © 2026 SAMDestroy</Copyright>

		<ComVisible>false</ComVisible>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	</PropertyGroup>
	<ItemGroup>
		<Compile Update="AVRControl.*.cs">
			<SubType>Code</SubType>
		</Compile>
		<Compile Update="AVRControl.cs" />
	</ItemGroup>
</Project>