<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>AVRControl</RootNamespace>
		<AssemblyName>AVRControl</AssemblyName>
		<ApplicationIcon>AVRControl.ico</ApplicationIcon>
		<Deterministic>true</Deterministic>

		<Version>1.5.1</Version>
		<Authors>SAMDestroy</Authors>
		<Company>SAMDestroy</Company>
		<Product>AVRControl</Product>
		<Description>Control your Denon or Marantz AVR via Telnet</Description>
		<Copyright>Copyright © 2026 SAMDestroy</Copyright>

		<ComVisible>false</ComVisible>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<CustomToolNamespace>Properties</CustomToolNamespace>
		</EmbeddedResource>
	</ItemGroup>


</Project>